name: Plugin
main: com.jediminer543.plugin.Plugin
version: 0.0.3
permissions:
    home.*:
      description: Gives access to the home and base system
      default: true
commands:
  sethome:
      description: Sends you back to your spawn.
      usage: /sethome
      permission: home.*
      permission-message: You need home permision to use this.
  home:
      description: Sends you back to your spawn.
      usage: /home
      permission: home.*
      permission-message: You need home permision to use this.
  spawn:
      description: Sends you back to your spawn.
      usage: /spawn
      permission: location.*
      permission-message: You need location control to use this.
  plugin:
      description: Sends you back to your spawn.
      usage: /plugin <command> [command parameters]
      permission: location.*
      permission-message: You need location control to use this.
  random:
      description: Sends you to a random location
      usage: /random [radius]
      permission: location.*
      permission-message: You need location control to use this.
  faction:
      description: Sends you back to your spawn.
      usage: /faction <command> [command parameters]
      permission: location.*
      permission-message: You need location control to use this.
    