name: Plugin
main: com.jediminer543.plugin.Plugin
version: 0.0.1
permissions:
    thing.*:
    description: Gives access to all thing commands
    default: true
commands:
   test:
      description: This is a test command.
      usage: /test
      permission: thing.*
      permission-message: You don't have