name: Plugin
main: com.jediminer543.plugin.Plugin
version: 0.0.3
permissions:
    home.*:
      description: Gives access to the home and base system
      default: true
commands:
  sethome:
      description: Sends you back to your spawn.
      permission: home.*
      permission-message: You need home permision to use this.
  home:
      description: Sends you back to your spawn.
      permission: home.*
      permission-message: You need home permision to use this.
  spawn:
      description: Sends you back to your spawn.
      permission: location.*
      permission-message: You need location control to use this.
    