name: Plugin
main: com.jediminer543.plugin.Plugin
version: 0.0.1
permissions:
    location.*:
      description: Gives access to all thing commands
      default: true
    thing.*:
      description: Gives access to all thing commands
      default: true
commands:
   test:
      description: This is a test command.
      usage: /test
      permission: thing.*
      permission-message: You don't have
   spawn:
      description: Sends you back to your spawn.
      usage: /spawn
      permission: location.*
      permission-message: You need location control to use this.